<?php
 /*
  * This module is a solution to the following coding challenge:
  *
  * 1. Display a block that shows the time the user last logged in. “You last logged in at “
  * 2. In the user’s current time-zone
  * 3. Have the block automatically be placed in left side-rail region (if available)
  * 4. Make sure that the block is not visible for non-logged in users.
  * 5. Allow the message to be configured per user.
  * 6. Frontend Javascript should collapse (animated) the block after 10 seconds.
  * 7. Make this a panels ctools content type (pane) in addition to a standard block
  * 8. Describe any issues or concerns you see with this list of requirements for this task in the context of a high traffic site like weather.com.
  *
  */

// implements hook_block_info

function weatheruser_block_info() {
  $blocks['loginstats'] = array(
    'info' => t('Login Stats'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

// implements hook_block_view

function weatheruser_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'loginstats':
      $out = "";
      global $user;

      // find values if available

      if ($user->uid>0) {
        $user_full = user_load($user->uid);
        $message = "You logged in at ";
        if (!empty($user_full->field_last_visited_message)) {
          $message = $user_full->field_last_visited_message['und'][0]['value'];
        }
        $zone = drupal_get_user_timezone();
        if (!empty($user->login)) {
          $last = format_date($user->login,'small',$zone);
        }
        $out = $message . " " . $last . " (" . $zone . ")";
      }

      // produce block

      $block['subject'] = t('Login Stats');
      $block['content'] = $out;
      break;
  }
  return $block;
}
